/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ingenieria1202610;

import figuras.ControladorCierre;
import figuras.SuccionadorDeColores;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Santiago
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    private PanelDeDibujo panelDeDibujo;

    public VentanaPrincipal() {
        initComponents();

        btnColorSegundoPlano.setBackground(Color.WHITE);
        btnColorPrimerPlano.setSelected(true);
        panelDeDibujo = new PanelDeDibujo();
        panelDeDibujo.setBackground(java.awt.Color.WHITE); // ← AGREGA ESTA
        panelDeDibujo.setOpaque(true);                     // ← AGREGA ESTA
        getContentPane().add(panelDeDibujo, java.awt.BorderLayout.CENTER);
        btnLapiz.addActionListener(e -> panelDeDibujo.setHerramienta("lapiz")); // 
        btnLinea.addActionListener(e -> panelDeDibujo.setHerramienta("linea"));
        btnBorrador.addActionListener(e -> panelDeDibujo.setHerramienta("borrador"));
        btnCuadrado.addActionListener(e -> panelDeDibujo.setHerramienta("rectangulo"));
        btnBotePintura.addActionListener(e -> panelDeDibujo.setHerramienta("balde"));
        btnPincel.addActionListener(e -> panelDeDibujo.setHerramienta("pincel"));

        panelDeDibujo.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {

                Color nuevoColor = panelDeDibujo.getColorDePrimerPlano();

                btnColorPrimerPlano.setBackground(nuevoColor);

                panelDeDibujo.setColorDePrimerPlano(nuevoColor);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHerramientas = new javax.swing.ButtonGroup();
        btnColores = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDeshacer = new javax.swing.JToggleButton();
        btnRehacer = new javax.swing.JToggleButton();
        btnRotar = new javax.swing.JToggleButton();
        btnBorrador = new javax.swing.JToggleButton();
        btnBotePintura = new javax.swing.JToggleButton();
        btnLapiz = new javax.swing.JToggleButton();
        btnLupa = new javax.swing.JToggleButton();
        btnLetras = new javax.swing.JToggleButton();
        btnSubsionadorColores = new javax.swing.JToggleButton();
        btnPincel = new javax.swing.JToggleButton();
        btnLinea = new javax.swing.JToggleButton();
        btnCuadrado = new javax.swing.JToggleButton();
        btnCruz = new javax.swing.JToggleButton();
        btnTriangulo = new javax.swing.JToggleButton();
        btnCirculo = new javax.swing.JToggleButton();
        btnLuna = new javax.swing.JToggleButton();
        btnExagono = new javax.swing.JToggleButton();
        btnEstrella = new javax.swing.JToggleButton();
        btnRombo = new javax.swing.JToggleButton();
        btnRayo = new javax.swing.JToggleButton();
        btnIndicacion = new javax.swing.JToggleButton();
        btnCorazon = new javax.swing.JToggleButton();
        btnColorPrimerPlano = new javax.swing.JToggleButton();
        btnColorSegundoPlano = new javax.swing.JToggleButton();
        btnColorRosado = new javax.swing.JToggleButton();
        btnColorBlanco = new javax.swing.JToggleButton();
        btnColorVerde = new javax.swing.JToggleButton();
        btnColorNaranja = new javax.swing.JToggleButton();
        btnColorVioleta = new javax.swing.JToggleButton();
        btnColorAmarillo = new javax.swing.JToggleButton();
        btnColorAzul = new javax.swing.JToggleButton();
        btnColorGris = new javax.swing.JToggleButton();
        btnNegro = new javax.swing.JToggleButton();
        btnColorRojo = new javax.swing.JToggleButton();
        btnPaletaDeColores = new javax.swing.JToggleButton();
        sliderGrosor = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        barraDeMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        btnNuevo = new javax.swing.JMenuItem();
        btnAbrir = new javax.swing.JMenuItem();
        btnGuardar = new javax.swing.JMenuItem();
        btnImprimir = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        btnCortar = new javax.swing.JMenuItem();
        btnCopiar = new javax.swing.JMenuItem();
        btnPegar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        btnAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 60, -1, -1));
        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 55, -1, -1));

        getContentPane().add(jPanel7, java.awt.BorderLayout.LINE_END);
        getContentPane().add(jPanel20, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Rotar");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel4.setText("Rehacer");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel5.setText("Deshacer");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setText("Pincel");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel1.setText("Heramientas");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 80, 20));

        jLabel2.setText("Formas ");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, 20));

        jLabel7.setText("Colores ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, 20));

        btnHerramientas.add(btnDeshacer);
        btnDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-deshacer-30.png"))); // NOI18N
        jPanel5.add(btnDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 60));

        btnHerramientas.add(btnRehacer);
        btnRehacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-rehacer-30.png"))); // NOI18N
        jPanel5.add(btnRehacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 60));

        btnHerramientas.add(btnRotar);
        btnRotar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-rotación-3d-30.png"))); // NOI18N
        jPanel5.add(btnRotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 60));

        btnHerramientas.add(btnBorrador);
        btnBorrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-borrador-24.png"))); // NOI18N
        jPanel5.add(btnBorrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, -1));

        btnHerramientas.add(btnBotePintura);
        btnBotePintura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-bote-de-pintura-24.png"))); // NOI18N
        btnBotePintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotePinturaActionPerformed(evt);
            }
        });
        jPanel5.add(btnBotePintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 50, -1));

        btnHerramientas.add(btnLapiz);
        btnLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-escribir-24.png"))); // NOI18N
        btnLapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapizActionPerformed(evt);
            }
        });
        jPanel5.add(btnLapiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, -1));

        btnHerramientas.add(btnLupa);
        btnLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-lupa-24.png"))); // NOI18N
        jPanel5.add(btnLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 50, -1));

        btnHerramientas.add(btnLetras);
        btnLetras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-letras-24.png"))); // NOI18N
        jPanel5.add(btnLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, -1));

        btnHerramientas.add(btnSubsionadorColores);
        btnSubsionadorColores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-cuentagotas-de-color-24.png"))); // NOI18N
        jPanel5.add(btnSubsionadorColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 50, -1));

        btnHerramientas.add(btnPincel);
        btnPincel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-pincel-24.png"))); // NOI18N
        jPanel5.add(btnPincel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 60, 60));

        btnHerramientas.add(btnLinea);
        btnLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-línea-de-llenado-30.png"))); // NOI18N
        btnLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineaActionPerformed(evt);
            }
        });
        jPanel5.add(btnLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 40, 30));

        btnHerramientas.add(btnCuadrado);
        btnCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-cuadrado-24.png"))); // NOI18N
        btnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoActionPerformed(evt);
            }
        });
        jPanel5.add(btnCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 40, -1));

        btnHerramientas.add(btnCruz);
        btnCruz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-hospital-30.png"))); // NOI18N
        jPanel5.add(btnCruz, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 40, 30));

        btnHerramientas.add(btnTriangulo);
        btnTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-triángulo-30.png"))); // NOI18N
        jPanel5.add(btnTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 40, 30));

        btnHerramientas.add(btnCirculo);
        btnCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-circulo-30.png"))); // NOI18N
        jPanel5.add(btnCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 30));

        btnHerramientas.add(btnLuna);
        btnLuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-luna-creciente-30.png"))); // NOI18N
        jPanel5.add(btnLuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 40, 30));

        btnHerramientas.add(btnExagono);
        btnExagono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-hexágono-30.png"))); // NOI18N
        btnExagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExagonoActionPerformed(evt);
            }
        });
        jPanel5.add(btnExagono, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, 30));

        btnHerramientas.add(btnEstrella);
        btnEstrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-estrella-30.png"))); // NOI18N
        jPanel5.add(btnEstrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 40, 30));

        btnHerramientas.add(btnRombo);
        btnRombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-rombo-30.png"))); // NOI18N
        jPanel5.add(btnRombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 40, 30));

        btnHerramientas.add(btnRayo);
        btnRayo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-rayo-30.png"))); // NOI18N
        jPanel5.add(btnRayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 40, 30));

        btnHerramientas.add(btnIndicacion);
        btnIndicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-derecha-30.png"))); // NOI18N
        jPanel5.add(btnIndicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 40, 30));

        btnHerramientas.add(btnCorazon);
        btnCorazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-me-gusta-30.png"))); // NOI18N
        jPanel5.add(btnCorazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 40, 30));

        btnColorPrimerPlano.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(btnColorPrimerPlano);
        btnColorPrimerPlano.setToolTipText("Color De Primer Plano");
        btnColorPrimerPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorPrimerPlanoActionPerformed(evt);
            }
        });
        jPanel5.add(btnColorPrimerPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 40, 30));

        buttonGroup1.add(btnColorSegundoPlano);
        btnColorSegundoPlano.setToolTipText("Color De Segundo Plano");
        btnColorSegundoPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorSegundoPlanoActionPerformed(evt);
            }
        });
        jPanel5.add(btnColorSegundoPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 40, 30));

        btnColorRosado.setBackground(new java.awt.Color(255, 0, 255));
        btnColores.add(btnColorRosado);
        jPanel5.add(btnColorRosado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, 20));

        btnColores.add(btnColorBlanco);
        jPanel5.add(btnColorBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, 20));

        btnColorVerde.setBackground(new java.awt.Color(0, 255, 0));
        btnColores.add(btnColorVerde);
        jPanel5.add(btnColorVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, 20));

        btnColorNaranja.setBackground(new java.awt.Color(255, 204, 0));
        btnColores.add(btnColorNaranja);
        btnColorNaranja.setToolTipText("");
        jPanel5.add(btnColorNaranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, 20));

        btnColorVioleta.setBackground(new java.awt.Color(204, 0, 0));
        btnColores.add(btnColorVioleta);
        jPanel5.add(btnColorVioleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, 20));

        btnColorAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        btnColores.add(btnColorAmarillo);
        jPanel5.add(btnColorAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, -1, 20));

        btnColorAzul.setBackground(new java.awt.Color(0, 0, 204));
        btnColores.add(btnColorAzul);
        jPanel5.add(btnColorAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, 20));

        btnColorGris.setBackground(new java.awt.Color(204, 204, 204));
        btnColores.add(btnColorGris);
        jPanel5.add(btnColorGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, -1, 20));

        btnNegro.setBackground(new java.awt.Color(0, 0, 0));
        btnColores.add(btnNegro);
        jPanel5.add(btnNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, 20));

        btnColorRojo.setBackground(new java.awt.Color(255, 51, 0));
        btnColores.add(btnColorRojo);
        jPanel5.add(btnColorRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, -1, 20));

        btnColores.add(btnPaletaDeColores);
        btnPaletaDeColores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-paleta-de-colores-48.png"))); // NOI18N
        btnPaletaDeColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaletaDeColoresActionPerformed(evt);
            }
        });
        jPanel5.add(btnPaletaDeColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 13, 60, 60));

        sliderGrosor.setMaximum(50);
        sliderGrosor.setMinimum(1);
        sliderGrosor.setValue(3);
        sliderGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderGrosorStateChanged(evt);
            }
        });
        jPanel5.add(sliderGrosor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 70, -1));

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        menuArchivo.setText("Archivo");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(btnNuevo);

        btnAbrir.setText("Abrir");
        menuArchivo.add(btnAbrir);

        btnGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(btnGuardar);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        menuArchivo.add(btnImprimir);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(btnSalir);

        barraDeMenu.add(menuArchivo);

        menuEdicion.setText("Edición");

        btnCortar.setText("Cortar");
        menuEdicion.add(btnCortar);

        btnCopiar.setText("Copiar");
        menuEdicion.add(btnCopiar);

        btnPegar.setText("Pegar");
        menuEdicion.add(btnPegar);

        barraDeMenu.add(menuEdicion);

        menuAyuda.setText("Ayuda");

        btnAcercaDe.setText("Acerca de");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(btnAcercaDe);

        barraDeMenu.add(menuAyuda);

        setJMenuBar(barraDeMenu);

        setBounds(0, 0, 1066, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ControladorCierre.confirmarCierre(this);
    }//GEN-LAST:event_formWindowClosing

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,
                "<html><b>Somos los estudiantes de Ingeniería 1</b><br>\n"
                + "Version 1.0<br>"
                + "Proyecto Paint \n",
                "Acerca de",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        ControladorCierre.confirmarCierre(this);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnExagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExagonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExagonoActionPerformed

    private void btnLapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLapizActionPerformed

    private void btnLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLineaActionPerformed


    private void btnSubsionadorColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubsionadorColoresActionPerformed
        panelDeDibujo.setHerramienta("succionador");
        panelDeDibujo.setCursor(SuccionadorDeColores.obtenerCursorCuentagotas());
    }//GEN-LAST:event_btnSubsionadorColoresActionPerformed

    private void btnPaletaDeColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaletaDeColoresActionPerformed
        Color color = JColorChooser.showDialog(this, "Seleccionar color", Color.black, false);

        if (color == null) {
            return;
        }

        System.out.println(color);
        if (btnColorPrimerPlano.isSelected()) {
            btnColorPrimerPlano.setBackground(color);
            panelDeDibujo.setColorDePrimerPlano(btnColorPrimerPlano.getBackground());
        } else {
            btnColorSegundoPlano.setBackground(color);
            panelDeDibujo.setColorDeSegundoPlano(
                    btnColorSegundoPlano.getBackground()
            );

        }
    }//GEN-LAST:event_btnPaletaDeColoresActionPerformed

    private void btnColorPrimerPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorPrimerPlanoActionPerformed
        Color colorTemp = btnColorPrimerPlano.getBackground();
        btnColorPrimerPlano.setBackground(btnColorSegundoPlano.getBackground());
        btnColorSegundoPlano.setBackground(colorTemp);

        panelDeDibujo.setColorDePrimerPlano(btnColorPrimerPlano.getBackground());
        panelDeDibujo.setColorDeSegundoPlano(btnColorSegundoPlano.getBackground());

    }//GEN-LAST:event_btnColorPrimerPlanoActionPerformed

    private void btnColorSegundoPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorSegundoPlanoActionPerformed
        Color colorTemp = btnColorPrimerPlano.getBackground();
        btnColorPrimerPlano.setBackground(btnColorSegundoPlano.getBackground());
        btnColorSegundoPlano.setBackground(colorTemp);

        panelDeDibujo.setColorDePrimerPlano(btnColorPrimerPlano.getBackground());
        panelDeDibujo.setColorDeSegundoPlano(btnColorSegundoPlano.getBackground());

    }//GEN-LAST:event_btnColorSegundoPlanoActionPerformed

    private void btnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCuadradoActionPerformed

    private void btnBotePinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotePinturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBotePinturaActionPerformed

    private void sliderGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderGrosorStateChanged
        panelDeDibujo.setGrosor(sliderGrosor.getValue());
    }//GEN-LAST:event_sliderGrosorStateChanged

    private void btnColorRosadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorRosadoActionPerformed
        miControlador.aplicarColorSecundario(new java.awt.Color(255, 0, 255));
    }//GEN-LAST:event_btnColorRosadoActionPerformed

    private void btnColorBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorBlancoActionPerformed
        miControlador.aplicarColorSecundario(java.awt.Color.WHITE);
    }//GEN-LAST:event_btnColorBlancoActionPerformed

    private void btnColorVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorVerdeActionPerformed
        miControlador.aplicarColorSecundario(java.awt.Color.GREEN);
    }//GEN-LAST:event_btnColorVerdeActionPerformed

    private void btnColorNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorNaranjaActionPerformed
        miControlador.aplicarColorSecundario(new java.awt.Color(255, 102, 0));
    }//GEN-LAST:event_btnColorNaranjaActionPerformed

    private void btnColorVioletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorVioletaActionPerformed
        miControlador.aplicarColorSecundario(new java.awt.Color(102, 0, 204));
    }//GEN-LAST:event_btnColorVioletaActionPerformed

    private void btnColorAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorAmarilloActionPerformed
        miControlador.aplicarColorSecundario(java.awt.Color.YELLOW);
    }//GEN-LAST:event_btnColorAmarilloActionPerformed

    private void btnColorAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorAzulActionPerformed
        miControlador.aplicarColorSecundario(java.awt.Color.BLUE);
    }//GEN-LAST:event_btnColorAzulActionPerformed

    private void btnColorGrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorGrisActionPerformed
        miControlador.aplicarColorSecundario(java.awt.Color.GRAY);
    }//GEN-LAST:event_btnColorGrisActionPerformed

    private void btnNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegroActionPerformed
        miControlador.aplicarColorSecundario(java.awt.Color.BLACK);
    }//GEN-LAST:event_btnNegroActionPerformed

    private void btnColorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorRojoActionPerformed
        miControlador.aplicarColorSecundario(java.awt.Color.RED);
    }//GEN-LAST:event_btnColorRojoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem btnAbrir;
    private javax.swing.JMenuItem btnAcercaDe;
    private javax.swing.JToggleButton btnBorrador;
    private javax.swing.JToggleButton btnBotePintura;
    private javax.swing.JToggleButton btnCirculo;
    private javax.swing.JToggleButton btnColorAmarillo;
    private javax.swing.JToggleButton btnColorAzul;
    private javax.swing.JToggleButton btnColorBlanco;
    private javax.swing.JToggleButton btnColorGris;
    private javax.swing.JToggleButton btnColorNaranja;
    private javax.swing.JToggleButton btnColorPrimerPlano;
    private javax.swing.JToggleButton btnColorRojo;
    private javax.swing.JToggleButton btnColorRosado;
    private javax.swing.JToggleButton btnColorSegundoPlano;
    private javax.swing.JToggleButton btnColorVerde;
    private javax.swing.JToggleButton btnColorVioleta;
    private javax.swing.ButtonGroup btnColores;
    private javax.swing.JMenuItem btnCopiar;
    private javax.swing.JToggleButton btnCorazon;
    private javax.swing.JMenuItem btnCortar;
    private javax.swing.JToggleButton btnCruz;
    private javax.swing.JToggleButton btnCuadrado;
    private javax.swing.JToggleButton btnDeshacer;
    private javax.swing.JToggleButton btnEstrella;
    private javax.swing.JToggleButton btnExagono;
    private javax.swing.JMenuItem btnGuardar;
    private javax.swing.ButtonGroup btnHerramientas;
    private javax.swing.JMenuItem btnImprimir;
    private javax.swing.JToggleButton btnIndicacion;
    private javax.swing.JToggleButton btnLapiz;
    private javax.swing.JToggleButton btnLetras;
    private javax.swing.JToggleButton btnLinea;
    private javax.swing.JToggleButton btnLuna;
    private javax.swing.JToggleButton btnLupa;
    private javax.swing.JToggleButton btnNegro;
    private javax.swing.JMenuItem btnNuevo;
    private javax.swing.JToggleButton btnPaletaDeColores;
    private javax.swing.JMenuItem btnPegar;
    private javax.swing.JToggleButton btnPincel;
    private javax.swing.JToggleButton btnRayo;
    private javax.swing.JToggleButton btnRehacer;
    private javax.swing.JToggleButton btnRombo;
    private javax.swing.JToggleButton btnRotar;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JToggleButton btnSubsionadorColores;
    private javax.swing.JToggleButton btnTriangulo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JSlider sliderGrosor;
    // End of variables declaration//GEN-END:variables
}
